# Generated by Django 4.0.4 on 2022-04-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_listtodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtodo',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.datetime', unique_for_date=True),
        ),
    ]
