# Generated by Django 4.0.4 on 2022-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_listtodo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetime',
            old_name='date',
            new_name='time',
        ),
    ]
