# Generated by Django 4.0.4 on 2022-04-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_date_datetime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtodo',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.datetime'),
        ),
    ]
