# Generated by Django 4.0.4 on 2022-04-27 10:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_listtodo_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='datetime',
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='datetime',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
