# Generated by Django 4.0.4 on 2022-04-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_datetime_managers_datetime_disable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetime',
            name='disable',
        ),
    ]
