# Generated by Django 4.0.4 on 2022-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_datetime_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtodo',
            name='finish',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
